name: Build Flutter Windows Executable

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Use the stable Flutter channel

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows Executable
        run: flutter build windows

      - name: Archive Executable
        run: |
          mkdir -p artifact
          cp -r ../build/windows/x64/runner/Release/chrome_dino.exe artifact/
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-exe
          path: artifact/
